### ISSUE TITLE
Include into Amber release

### ISSUE THREAD

**Issue by SSchott** [liedllab/gigist#10]
Hi,

If I understand correctly, this code has changes over the original one included in cpptraj. Any reason why this has not been further pushed there? Should it be included?

**Comment by fwaibl** [comment]
Hi,

in fact, most of the changes here have been included in cpptraj over the time (e.g., the GPU implementation, extension to multiple solvents, numerical improvements to the entropy calculation). The version in cpptraj is by now better tested and should be used in favor of GIGIST. Is there any specific feature that you are missing in the cpptraj implementation?

Best,
Franz

**Comment by SSchott** [comment]
Thanks for the prompt reply. Is just that I wanted to use GIST again, and remember that some time ago I got different results between the included version and this one. It seems that since then indeed the codes are closer. I just ran a test, and seems to be on par, except with the sum for dTS, with 13% difference as summed with gistpp. Now this is with different cpptraj versions and compiled with different CUDAs, but is that expected?

**Comment by fwaibl** [comment]
It is up to you whether the 13% difference is acceptable. I assume that there is mostly a small offset which adds to a large difference because you sum over bulk regions, where the entropy is close to zero and small absolute differences lead to large relative ones.

Two differences between cpptraj and GIGIST come to my mind:
1) For the six-dimensional entropy, GIGIST always finds the 6-D nearest neighbor, while the cpptraj version only searches in neighboring voxels, which is faster but can lead to a slight inaccuracy. You can improve this in cpptraj by setting nnsearchlayers to a high number (anything above 2 should be basically the same). This should make the results consistent with GIGIST.
2) Both cpptraj and GIGIST compute the quaternion product in single precision. But cpptraj has an additional step where this value is re-normalized in double precision, which makes the distance metric more accurate. This might lead to an additional small offset in the bulk entropy. In this case, cpptraj should be more accurate.

To deal with this difference in post-processing, we had good experience subtracting a reference value from the entropy (analogous to the Eww reference), just to avoid accumulation of entropy from numerical inaccuracies.

**Comment by SSchott** [comment]
Great, makes sense, thanks for the insights!

**Comment by fwaibl** [comment]
Actually I just checked, and it seems that the neighbor search is also set to 1 layer in GIGIST. So that would be consistent with the cpptraj default. In any case, you can see if changing nnsearchlayers makes a difference for you.
